### ISSUE TITLE
missing header

### ISSUE THREAD

**Issue by tiralonghipol** [fzi-forschungszentrum-informatik/vdb_mapping#1]
hi, 
when try to build the package, I check the following error:
```
fatal error: openvdb/Types.h: No such file or directory
   35 | #include <openvdb/Types.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

any tips?

**Comment by MGBla** [comment]
Hey,
my first guess would be some problem with your openvdb installation. Have you installed libopenvdb-dev?

**Comment by tiralonghipol** [comment]
yes! now the headers are found correctly
but I seem to have a linking problem:

``` 
undefined reference to `openvdb::v6_2:: XXXX

```

this appens for a lot of openvdb libraries
I assume you have never seen this error?
im in Ubuntu 20, Linux 5.11.0-41-generic

**Comment by tiralonghipol** [comment]
solved building openvdb from source

**Comment by YoshuaNava** [comment]
@tiralonghipol did you try installing the developer version of the OpenVDB library?

For example, in Ubuntu you can do that by running:

`sudo apt install libopenvdb-dev`
