### ISSUE TITLE
cmake failed on ubuntu 22.04

### ISSUE THREAD

**Issue by changyuan79** [fzi-forschungszentrum-informatik/vdb_mapping#5]
I cloned the git repo and tried to build it on ubuntu 22.04. The cmake log said that
Could not find mpi (missing: MPI_FOUND_C) 
  Reason given by package: mpi component 'c' was requested, but language c is not enabled.

It was because the project languages in CMakeLists.txt only contained "C++", but not "C". Once I changed it to:
project(vdb_mapping CXX C)
cmake could build successfully. Could you please add "C" to CMakeLists.txt? Thank you!

**Comment by lucasw** [comment]
I made this branch with that change: https://github.com/lucasw/vdb_mapping/tree/ubuntu_2304 (I'm using 23.04)

But it still doesn't build, it wants `-lHalf` and I'm not seeing that in 23.04- there's `libghc-half-dev - half-precision floating-point` but it doesn't have a libHalf.so in it.

**Comment by lucasw** [comment]
Now it builds in 23.04 with `-lImath` instead of `-lHalf`

**Comment by MGBla** [comment]
Hey Lucas, Thanks for the fix. I will have a look at it tomorrow when I'm back at my laptop. Have already set up a container with 23.04 and will test around with compabilities to older OS.

**Comment by MGBla** [comment]
Closed by #6

**Comment by MGBla** [comment]
Closed by #6
